import React, { Component } from 'react'

export class Landing extends Component {
  
    render() {
      
    return    React.createElement('div', {className:"wrapper"},
    React.createElement('div', { className:"table basic"},
    React.createElement('div', { className:"package-name"}),
    React.createElement('div', { className:"features"},
    React.createElement('span', null," FREE" ),
    React.createElement('br', null ),
    React.createElement('span', {className:"price"}," $0/month" ),
    
    React.createElement('ul', null,
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Single User" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," 50GB Storage" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Unlimited Public Projects" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"},"Community Access" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon cross"}),
    React.createElement('span', { className:"list-name cross" }," Unlimited Private Project" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon cross"}),
    React.createElement('span', { className:"list-name cross"}," Dedicated Phone Support" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon cross"}),
    React.createElement('span', { className:"list-name cross"}," Free Subdomain" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon cross"}),
    React.createElement('span', { className:"list-name cross"}," Monthly status Report" ))),
    React.createElement('button', { className:"btn"}," BUTTON" ))),
    React.createElement('div', { className:"table basic"},
    React.createElement('div', { className:"package-name"}),
    React.createElement('div', { className:"features"},
    React.createElement('span', null," PLUS" ),
    React.createElement('br', null ),
    React.createElement('span', {className:"price"}," $9/month" ),
    React.createElement('ul', null,
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," 5 Users" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," 50GB Storage" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Unlimited Public Projects" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"},"Community Access" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name" }," Unlimited Private Project" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Dedicated Phone Support" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Free Subdomain" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon cross"}),
    React.createElement('span', { className:"list-name cross"}," Monthly status Report" ))),
    React.createElement('button', { className:"btn"}," BUTTON" ))),
    React.createElement('div', { className:"table basic"},
    React.createElement('div', { className:"package-name"}),
    React.createElement('div', { className:"features"},
    React.createElement('span', null," PRO" ),
    React.createElement('br', null ),
    React.createElement('span', {className:"price"}," $49/month" ),
    React.createElement('ul', null,
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Unlimited Users" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," 50GB Storage" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Unlimited Public Projects" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"},"Community Access" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name" }," Unlimited Private Project" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Dedicated Phone Support" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Free Subdomain" )),
    React.createElement('li', null,
    React.createElement('span', { className:"icon check"}),
    React.createElement('span', { className:"list-name"}," Monthly status Report" ))),
    React.createElement('button', { className:"btn" }," BUTTON" )))
    )
  }
}

export default Landing